title: Sheridan Cheese Factory
description: A website documenting the history of the Sheridan Cheese Factory
baseurl: "/SheridanCheeseFactory" # the subpath of your site, e.g. /blog
url: "https://SheridanCheeseFactory.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/images/purchase.jpg"

remote_theme: just-the-docs/just-the-docs
